name: Clang-CL Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-clang-cl:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup LLVM 22
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: "22"

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "latest"

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DBUILD_DEMO=OFF

      - name: Build
        run: cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure