name: Apple Clang
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-clang-macos:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.25.1"

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: |
          export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DBUILD_TESTING=ON

      - name: Build
        working-directory: build
        run: cmake --build . -j$(sysctl -n hw.ncpu)

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
