name: LLVM Clang:19 Linux
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-clang:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LLVM and Clang 19
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
          sudo apt-get update
          sudo apt-get install -y clang-19 libc++-19-dev libc++abi-19-dev lld-19
          clang-19 --version

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.25.1"

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_C_COMPILER=clang-19 -DBUILD_TESTING=ON

      - name: Build
        working-directory: build
        run: cmake --build . -j$(nproc)

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
