name: GCC:14
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gcc:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: gcc:14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.25.1"

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBUILD_DEMO=OFF

      - name: Build
        working-directory: build
        run: cmake --build . -j$(nproc)

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
