name: MSVC Windows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-msvc:
    name: Build and Test (MSVC)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.31.3"

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        working-directory: build
        run: cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build with MSVC
        working-directory: build
        run: cmake --build . --config Release

      - name: Run tests
        working-directory: build
        run: ctest -C Release --output-on-failure
